name: Mi Primer Workflow

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Ejecutar comando
      run: echo "¡Hola, GitHub Actions!"
