name: Mi Primer Workflow

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Ejecutar comando
      run: echo "¡Hola, GitHub Actions!"
      #test pipeline
    - name: Install Python requirements
      uses: aabadie/action-install-python-requirements@v2.0.1
      with:
        requirements: requirements.txt
        update-pip: true
        
    - name: Listar paquetes instalados
      run: pip list

    - name: Convertir notebook a PDF
      run: |
        sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic -y
        pip install nbconvert
        jupyter nbconvert --to pdf ARIMA_TS.ipynb
