name: Generar y subir PDF de Notebook

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-plain-generic \
          pandoc

    - name: Instalar dependencias de Python
      run: |
        pip install nbconvert pandas matplotlib

    - name: Convertir notebook a PDF
      run: |
        jupyter nbconvert --to pdf ARIMA_TS.ipynb --no-input

    - name: Listar archivos generados
      run: ls -la
