name: Clonar Repositorio en VM

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Verificar archivos clonados
        run: ls -la
